export const CHANGE_VALUE = "CHANGE_VALUE";
export const CHANGE_INPUT_NUMBER_SYSTEM = "CHANGE_INPUT_NUMBER_SYSTEM";
export const CHANGE_OUTPUT_NUMBER_SYSTEM = "CHANGE_OUTPUT_NUMBER_SYSTEM";
export const SWITCH_OUTPUT_NUMBER_SYSTEM = "SWITCH_OUTPUT_NUMBER_SYSTEM";
export const CONVERT_REQUEST = "CONVERT_REQUEST";
export const CONVERT_SUCCESS = "CONVERT_SUCCESS";
export const CONVERT_FAILURE = "CONVERT_FAILURE";
export const SWITCH_VALID_CONVERT = "SWITCH_VALID_CONVERT";

export const CHANGE_START_DATE = "CHANGE_START_DATE";
export const CHANGE_END_DATE = "CHANGE_END_DATE";
export const HISTORY_REQUEST = "HISTORY_REQUEST";
export const HISTORY_SUCCESS = "HISTORY_SUCCESS";
export const HISTORY_FAILURE = "HISTORY_FAILURE";

export const ADD_CHAR = "ADD_CHAR";
export const REMOVE_CHAR = "REMOVE_CHAR";
export const REMOVE_ALL = "REMOVE_ALL";
export const SWITCH_SIGN = "SWITCH_SIGN";
export const CALCULATE_REQUEST = "CALCULATE_REQUEST";
export const CALCULATE_SUCCESS = "CALCULATE_SUCCESS";
export const CALCULATE_FAILURE = "CALCULATE_FAILURE";
export const SWITCH_VALID_STANDART = "SWITCH_VALID_STANDART";

export const LOGOUT = "LOGOUT";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const FETCH_MY_DATA_REQUEST = "FETCH_MY_DATA_REQUEST";
export const FETCH_MY_DATA_SUCCESS = "FETCH_MY_DATA_SUCCESS";
export const FETCH_MY_DATA_FAILURE = "FETCH_MY_DATA_FAILURE";
